---
version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      cluster.name: "cspreporter"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
