---
version: '3'

services:

  cspr-collector:
    image: mhilker/cspr-collector:latest
    build:
      context: ../..
      dockerfile: cmd/cspr-collector/Dockerfile
    command: --host 0.0.0.0:8080 -output-stdout -output-es -output-es-host "http://elasticsearch:9200/"
    ports:
      - 8080:8080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.2
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      cluster.name: "cspr-collector"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.3.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
